### PR TITLE
Update Sony - PlayStation 2.json

### PR DESCRIPTION
**Pull request by rufotheone-fr**
About "Attack of the Toybots":
`Nicktoons - Attack of the Toybots` is an english only release for the PAL zone (both EU and AUS) but `Nickelodeon SpongeBob and Friends - Attack of the Toybots` is a Multi6 release for Europe (no Australia but it's exactly the same game, minus the title screen). Retool only takes the `Nicktoons` instead of the other one with the previous setting (treating `Nickelodeon SpongeBob and Friends - Attack of the Toybots` as a regional equivalent)... What I'm trying to do here, by putting 0 in the line of `Nickelodeon SpongeBob and Friends - Attack of the Toybots` is to give this release the priority because any PAL player can give this one a go instead of `Nicktoons` which is english only.

### CODE REVIEW

**Comment by unexpectedpanda** [comment]
Ah, I see.

I think this sits in a weird grey area of current and future functionality. By making this change now, I'd have to remember to change it back later. Basically, this is something that I'm trying to handle in code, not clone lists.

I'm going to keep this PR open to remind me to dig into it. I know I've got other NTSC vs PAL work to explore, and this falls neatly under that umbrella.

**Comment by rufotheone-fr** [comment]
Ok I'll report that in an issue and kick the Spongebob part so we can merge the other fixes.

**Comment by rufotheone-fr** [comment]
Maybe it will be a good time to merge, no? ^^;

**Comment by unexpectedpanda** [comment]
Truthfully I've been avoiding updates as it means I have to do the work twice while I'm migrating to v2 😱

Having said that, it keeps dragging out... so I suppose I can't avoid it any longer :) Thanks for the poke.

**Pull request merged**
