### PR TITLE
Update Sony - PlayStation.json

### PR DESCRIPTION
**Pull request by rufotheone-fr**

### CODE REVIEW

**Comment by unexpectedpanda** [comment]
What's the thinking on this one? I try to avoid removes wherever possible.

**Comment by rufotheone-fr** [comment]
I thought that you'd prefer it this way because the remove section is pretty populated ^^;
I can set those to 2 and drop them in their respective games.

**Comment by unexpectedpanda** [comment]
Ideally, removes should only be used if the issue can't be solved any other way. Otherwise, it's better to leave titles associated with their groups. This is because when you remove something, Retool doesn't have the chance later to select a title due to user preferences (unless someone does a custom include, but that's another story...).

Looks like those removes are mostly there because you were initially [trying to handle compilations](https://github.com/unexpectedpanda/retool/pull/145#issuecomment-981040222), which can be a real pain (and a valid choice!). I'm working on making compilations easier in v2 right now... the logic is done, but it needs to be faster.

Additionally, in this case, [EZ is an expanded version of the original](https://github.com/unexpectedpanda/retool/pull/154). You probably want something like:

```
"Carnage Heart": [
    [Carnage Heart EZ (Easy Zapping)", 0],
    ["SuperLite 1500 Series - Carnage Heart EZ (Easy Zapping)", 0],
    ["SuperLite 1500 Series - Carnage Heart", 2]
],
```

**Comment by rufotheone-fr** [comment]
I reminded the purpose of the remove section while I was sleeping ^^;
Reverted!

**Pull request merged**
